server:
  port: 8888

spring:
  application:
    name: Gateway2
  cloud:
    discovery:
      enabled: true    # Désactive la découverte de service
   # gateway:
    #  routes:
     #   - id: r1
      #    uri: http://localhost:8081
       #   predicates:
        #    - Path= /customers/**

        #- id: r2
         # uri: http://localhost:8085
          #predicates:
           # - Path= /products/**